#!/usr/bin/env python3
"""Generates Sources/FITStudioCore/FITProfileData.swift from the Garmin FIT SDK's profile.

The app needs each field's name, scale, offset and units to show values in real units and to
scale them correctly, plus the names of enum values (sports, manufacturers, products). This copies
them out of the official SDK so nothing is typed in by hand.

Usage:
    python3 -m venv .venv && .venv/bin/pip install garmin-fit-sdk
    .venv/bin/python scripts/generate_profile.py > Sources/FITStudioCore/FITProfileData.swift
"""
from garmin_fit_sdk.profile import Profile

NUMERIC = {"sint8", "uint8", "sint16", "uint16", "sint32", "uint32", "float32", "float64",
           "uint8z", "uint16z", "uint32z", "sint64", "uint64", "uint64z"}


def one(values, default):
    """Scale, offset and units are lists for fields with components; the field's own value only
    uses them when there is exactly one (same rule as the SDK's decoder)."""
    if isinstance(values, list):
        return values[0] if len(values) == 1 else default
    return values if values not in (None, "") else default


def number(value):
    text = repr(float(value))
    return text[:-2] if text.endswith(".0") else text


def clean(text):
    text = str(text)
    assert "|" not in text and "\\" not in text and '"""' not in text and "\n" not in text, text
    return text


def main():
    version = Profile["version"]
    lines = []
    lines.append("// Generated by scripts/generate_profile.py from the Garmin FIT SDK profile "
                 f"{version['major']}.{version['minor']}. Do not edit by hand.")
    lines.append("// Field rows: message|field|name|type|base type|array|scale|offset|units")
    lines.append("// Type rows: type|value|name")
    lines.append("")
    lines.append("extension FITProfile {")
    lines.append(f'    public static let version = "{version["major"]}.{version["minor"]}"')
    lines.append("")

    lines.append('    static let messageRows = """')
    for num, message in sorted(Profile["messages"].items()):
        lines.append(f"    {num}|{clean(message['name'])}")
    lines.append('    """')
    lines.append("")

    lines.append('    static let fieldRows = """')
    for num, message in sorted(Profile["messages"].items()):
        for field_num, field in sorted(message["fields"].items()):
            base = field["base_type"]
            scale = one(field["scale"], 1) if field["type"] in NUMERIC else 1
            offset = one(field["offset"], 0) if field["type"] in NUMERIC else 0
            units = one(field["units"], "")
            lines.append("    " + "|".join([
                str(num), str(field_num), clean(field["name"]), clean(field["type"]), clean(base),
                "1" if field["array"] == "true" else "0", number(scale), number(offset), clean(units),
            ]))
    lines.append('    """')
    lines.append("")

    lines.append('    static let typeRows = """')
    for type_name, values in Profile["types"].items():
        if type_name == "mesg_num":
            continue  # same as the message names above
        for value, name in values.items():
            lines.append(f"    {clean(type_name)}|{int(value)}|{clean(name)}")
    lines.append('    """')
    lines.append("}")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
